language: node_js

node_js:
  - stable

install:
  - npm install

script:
  - npm run build

deploy:
  local_dir: ./dist
  provider: pages
  skip_cleanup: true
  email: $U_EMAIL
  name: $U_NAME
  github_token: $GH_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: false
  on:
    branch: master
